ignored:
  - DL3008   # pin versions in apt-get (optional; du pinnst via base image)
  - DL3018   # pin versions in apk/apt (optional)
  - DL3045   # no sudo in container (irrelevant)
  - DL3003   # use WORKDIR (du nutzt es bereits meist)
failure-threshold: warning
