version: "3.8"

services:
  rsyslog:
    build:
      #context: ./rsyslog
      dockerfile: Dockerfile-rsyslog
    environment:
      - TZ=${TZ}      
    ports:
      - "${SYSLOG_UDP_PORT}:514/udp"
      - "${SYSLOG_TCP_PORT_601}:514/tcp"
    volumes:
      - ./data/rsyslog/config:/etc/rsyslog.d/
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped

  loganalyzer:
    build:
      #context: ./loganalyzer
      dockerfile: Dockerfile-loganalyzer
      args:
        LOGANALYZER_VERSION: ${LOGANALYZER_VERSION}
    image: loganalyzer:${LOGANALYZER_VERSION}
    environment:
      - TZ=${TZ}
    ports:
      - "${LOGANALYZER_PORT}:80"
    volumes:
      - ./data/syslog/log/:/var/log/
      - ./data/loganalyzer/config/config.php:/var/www/html/config.php
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped

  database:
    image: mariadb:latest
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - TZ=${TZ}
    healthcheck:
      test: ["CMD-SHELL", "mariadb -u root -p$${MARIADB_ROOT_PASSWORD} -e 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - dbdata:/var/lib/mysql
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql    

volumes:
  dbdata: