FROM php:8.2-apache
ENV DEBIAN_FRONTEND=noninteractive

ARG LOGANALYZER_VERSION
ENV LOGANALYZER_VERSION=${LOGANALYZER_VERSION}

# benötigte PHP-Extensions
RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      curl \
      unzip \
      tzdata \
      ca-certificates \
 && docker-php-ext-install \
      mysqli pdo pdo_mysql \
 #&& a2enmod rewrite expires \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

# Loganalyzer kopieren
COPY ./resources/loganalyzer-${LOGANALYZER_VERSION}/src/ /var/www/html/

# Zugriffsrechte setzen
RUN chown -R www-data:www-data /var/www/html && chmod -R 755 /var/www/html