FROM debian:bookworm

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    syslog-ng \
    syslog-ng-mod-sql \
    libdbi1 \
    libdbd-mysql \
    mariadb-client \
    tzdata \
    && apt-get clean

#COPY syslog-ng.conf /etc/syslog-ng/syslog-ng.conf

CMD ["syslog-ng", "-F", "--no-caps"]
