version: "3.8"

services:
  syslog-ng:
    build:
      context: ./syslog-ng
      dockerfile: Dockerfile
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TZ}
    volumes:
      - ./data/syslog-ng/config:/config
      - ./data/syslog-ng/log:/var/log
    ports:
      - "${SYSLOG_UDP_PORT}:5514/udp"
      - "${SYSLOG_TCP_PORT_601}:6601/tcp"
      - "${SYSLOG_TCP_PORT_6514}:6514/tcp"
    restart: unless-stopped

  loganalyzer:
    build:
      context: .
      dockerfile: Dockerfile
    image: loganalyzer:${LOGANALYZER_VERSION}
    ports:
      - "${LOGANALYZER_PORT}:80"
    environment:
      - TZ=${TZ}
    volumes:
      - ./data/syslog/log/:/var/log/
    depends_on:
      - database
    restart: unless-stopped

  database:
    image: mariadb:latest
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - mariadbdata:/var/lib/mysql
      - ./data/db-init.sql:/docker-entrypoint-initdb.d/init.sql      
    networks:
      - backend-nw

volumes:
  mariadbdata:

networks:
  backend-nw:
    driver: bridge